name: slide_puzzle
publish_to: none
version: 1.0.0

environment:
  sdk: ^3.12.0

dependencies:
  collection: ^1.19.1
  flutter:
    sdk: flutter
  http: ^1.2.0
  provider: ^6.0.2
  url_launcher: ^6.3.0

dev_dependencies:
  dart_flutter_team_lints: ^3.0.0
  flutter_test:
    sdk: flutter
  test: ^1.24.0

flutter:
  uses-material-design: true
  assets:
    - asset/

  fonts:
    - family: Plaster
      fonts:
        - asset: asset/fonts/plaster/Plaster-Regular.ttf
