name: slide_puzzle

version: 1.0.0

environment:
  sdk: ^3.12.0

dependencies:
  flutter:
    sdk: flutter
  provider: ^6.0.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  pedantic: ^1.11.0
  test: ^1.24.0
  stats: ^3.0.0

flutter:
  uses-material-design: true
  assets:
    - asset/

  fonts:
    - family: Plaster
      fonts:
        - asset: asset/fonts/plaster/Plaster-Regular.ttf
